CREATE SEQUENCE bank_id_sequence
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 20000000
START WITH 1
CYCLE;

CREATE SEQUENCE settlement_account_id_sequence
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 20000000
START WITH 1
CYCLE;

CREATE SEQUENCE pay_initiation_id_sequence
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 20000000
START WITH 1
CYCLE;

CREATE SEQUENCE file_download_id_sequence
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 20000000
START WITH 1
CYCLE;